ALPACA_API_KEY = "PK77EJ5F7LSKKVXUVAQAOQFTKC"
ALPACA_SECRET_KEY = "E4wMWBRW6b2io15NNqS5AvmFSYHscEgVYGuUPVtPwWNw"

NEWS_API_KEY = "649bc159ad884acbac1349a6084b2556"

EMAIL_FROM = "giselltavarez@gmail.com"
EMAIL_TO = "giselltavarez@gmail.com"
EMAIL_PASSWORD = "jzhbiyhsqivbvflw"
SMTP_SERVER = "smtp.gmail.com"
SMTP_PORT = "587"