

NEWS_API_KEY = "649bc159ad884acbac1349a6084b2556"

EMAIL_FROM = "giselltavarez@gmail.com"
EMAIL_TO = "giselltavarez@gmail.com"
EMAIL_PASSWORD = "jzhbiyhsqivbvflw"
SMTP_SERVER = "smtp.gmail.com"
SMTP_PORT = "587"